val_rate: 0.25
image_width: 1024
image_height: 1024
original_images_dir: './data/originals/'
test_dir: './data/images/test/'
test_weights: './runs/detect/train+n+1024+multi/weights/best.pt'
# labels_dict: {'Atelectasis': 1, 'Cardiomegaly': 1, 'Effusion': 1, 'Infiltrate': 1, 'Mass': 1, 'Nodule': 1, 'Pneumonia': 1, 'Pneumothorax': 1}
labels_dict: {'Atelectasis': 1, 'Cardiomegaly': 2, 'Effusion': 3, 'Infiltrate': 4, 'Mass': 5, 'Nodule': 6, 'Pneumonia': 7, 'Pneumothorax': 8}